.config/i3/config
.config/i3/i3_guide.md
.config/i3/kb-lights.py
.config/mutt/gmailrc
.vimrc

…ht keybinds not being configured correctly.
Fixes issue with spelling in the i3_guide.md file.
This commit adds comments to gmailrc file to alert users to danger of using their defualt plaintext password, and suggests generating a new app password.
This closes #1, closes #6, closes #8, closes#11

 Adds support for Spotify controls. Fixes all known issues.

---

.config/Scripts/extract

Fixed the extract script and added description for two possible ways the script can operate.

Fixed the extract script

---

.config/i3/config

And use $netrefresh for XF86WLAN

Shutdown, reboot and NM restart for runit

---

.config/qutebrowser/config.py

Changed /home/luke to ~/

---

.bash_profile

This is meant for https://github.com/LukeSmithxyz/LARBS/issues/29

Bug fix: $PATH sometimes breaks from package conflicts

---

.scripts/crontog

Hello. I like having time without any mail notifications and binding this in my i3 config so I can access that quickly but also I want to know the status of that so that's where crontog comes to.

Add notify-send in crontog

---

.scripts/linkhandler

Now you can get two for the price of one!
Tested using the example on your blog.

Change sci-hub command to use 1 perl-style grep

---

.config/i3/config

Allows for shift + the keyboard control to increase the magnitude of volume changed and control to decrease it.

Enhanced Extra XF86 Keys Volume Control

---

.config/newsboat/config

Update newsboat config as well

---

.config/i3/config
.config/i3blocks/config
.scripts/cron/newsup
.scripts/statusbar/i3news

Added unread functionality for newsboat in statusbar.

newsboat unread statusbar

---

.scripts/i3cmds/ducksearch

Thanks for the great content on youtube and for sharing your efforts!
Here's a modification to the ducksearch script. If the user inserts a url to the dmenu prompt, the script now attempts to recognize that and sends the unformatted query to the browser.

Detect http urls in ducksearch and directly connect to them

---

.scripts/statusbar/clock
.scripts/statusbar/pacpackages

Some statusbar additions, check commit comments.

Statusbar additions

---

.bashrc

https://wiki.archlinux.org/index.php?title=Lp&redirect=no

lp is already used by CUPS

---

.readme.mom

Pretty small, but had me stumped first reading the document.

Fixes readme typo for tutorialvid shortcut

---

.config/getkeys/i3
.config/getkeys/i3keysguide

Updated the getkeys/i3 to match the i3 config.

Changed $mod+Shift+r shortcut to winresize

---

.config/getkeys/i3

Hi @LukeSmithxyz ,
I am starting playing with i3wm and using your LARBS. Big thumbs up and thank you for your work! Since I am new I used `getkeys i3` often.
I noticed that some keybinding were not updated in the `getkeys i3` listing.

update getkeys i3 help

---

.scripts/cron/checkup

fix spelling

---

.scripts/tools/ifinstalled

Fixed ifinstalled command after [dunst update](https://github.com/LukeSmithxyz/voidrice/commit/339d7bb468c217fae4c6b119650d47a9f6c7faf4).

Fixed ifinstalled command after dunst update.

---

.config/sxhkd/sxhkdrc

Fixed typo in sxhkdrc

---

.config/sxhkd/sxhkdrc

Removed extra "g". (for voiddwm)

Fixed typo in sxhkdrc (voiddwm)

---

.local/bin/dwmbar
.local/bin/refbar

True chads use signals and traps.
No, seriously, it's much more efficient.

Refreshing dwm status bar using signals.

---

.config/sxhkd/sxhkdrc

This was butchered in 425941bf697ac4e38cdcc352799b1a61ebb8d34c

Add the media keys to sxhkd config

---

.config/nvim/init.vim

System clipboard copy paste using xclip.Neovim doesn't require gvim.Use traditional yank and paste

System clipboard copy/paste using xclip.

---

.config/sxhkd/sxhkdrc
.local/bin/statusbar/clock

CALCURSE SXHDRC FIX

---

.local/bin/statusbar/music

use tail -r instead of tac

---

.local/bin/statusbar/music

Reverts LukeSmithxyz/voidrice#360

Revert "use tail -r instead of tac"

---

.local/bin/statusbar/battery
.local/bin/statusbar/disk
.local/bin/statusbar/internet

According to https://github.com/vivien/i3blocks/issues/393

added \n to printf (forced by i3blocks 1.5)

---

.local/bin/statusbar/music

Add the \n character after the </span> so the music block appears again.

Music block fix for i3blocks

---

.config/polybar/config

replace hard-coded terminal reference with $TERMINAL environment var

Make polybar more portable

---

.local/bin/dmenumount

Some android phones ask for permission to allow access to phone data.

Allow access to phone date

---

.local/bin/statusbar/moonphase

8 emoji for 8 main phases plus the % 'of full'
😉 dont forget to load it to your status bar

know the phase of the moon with emoji and %

---

.local/bin/statusbar/moonphase

Now accepts a date as argument, to know pom of a diff date.
Corrected some typos, and a logic error of mine 😄

Updated moonphase

---

.local/bin/statusbar/battery

It looks more mass appealing  with the details.

Added instructive suggestion in the comments

---

.local/bin/setbg

Filter the pictures in directory by file extensions

Just find pictures

---

.config/vifm/vifmrc

Fixed a litle typo

---

.local/bin/statusbar/moonphase

right click to open notification
left & middle to update
fixes specific dates

🌜updated moonphase🌛

---

.local/bin/statusbar/memory

see issue number #535 
(there is maybe a more efficient way, doing it only in one command, but this is just to bring it to your attention.)

memory statusbar with multilanguage support

---

.config/aliasrc
.config/lf/lfrc
.config/mpv/scripts/modules.lua
.config/ranger/rifle.conf
.config/vifm/vifmrc
.gitmodules
.local/bin/dmenuhandler
.local/bin/linkhandler
.local/bin/pauseallmpv

mpv config: use mpvSockets script to remove mpv wrappers/aliases

---

.config/nvim/init.vim

https://github.com/LukeSmithxyz/voidrice/issues/561

autocmd to delete newlines at end of file on save.

---

.local/bin/statusbar/battery
.local/bin/statusbar/disk
.local/bin/statusbar/news
.local/bin/statusbar/pacpackages
.local/bin/statusbar/torrent

Fix minor statusbar issues

---

.config/nvim/init.vim

Visually intuitive for editing hex color codes in Xresources /XDefaults  and anywhere else

Plugin to highlight hex color codes

---

.local/bin/statusbar/clock

i made it so it will give you an emoji for the main 12 hours. there are also halfs (one-thirty 🕜,six thirty 🕡...) though idk how to do it, other than in a bloated 'if for every one'-way.
also added an option for europeans, and made that cleaner.

Clock with auto change emoji

---

.config/directories
.zprofile

next PR will use this variable

$XDG_CACHE_HOME env variable

---

.local/bin/sysact

See #584.
I changed it to the simplest fix.

Fix sysact

---

.local/bin/i3cmds/toggle-welcome

It would not run if you removed ~/.xprofile, so i changed `~/.xprofile` to `$XDG_CONFIG_HOME/xprofile`

update for welcome toggle

---

.config/mpd/mpd.conf

After pulling the new version of LARBS, I could no longer listen to music. I noticed that Luke moved many things to Pulseaudio but mpd.conf was left behind. This fixed the music issue for me.
Feel free to implement it in a better way if there is :)

Changes to mpd.conf to support pulseaudio

---

.local/bin/statusbar/crypto

i was fiddling with the block settings and couldnt get it to display on i3 until i just added the new line. also tested on the dwm build, module acts as it should on dem with this change

new line needed to work on i3

---

.local/bin/compiler

Of course, for proper unicode support you'd need neatroff or really any other troff :)

run preconv and pipe its output into refer to prevent unicode problems

---

.local/bin/statusbar/nettraf

it would not run without an existing nonempty log file

create netlog if empty

---

.local/bin/linkhandler

Missing ; added to setsid -f
Same problem as [This commit](https://github.com/LukeSmithxyz/voidrice/commit/bc28b6bc7076e4007302734bb59f0d8003914bd0)

Another lol fix

---

.local/bin/statusbar/music

fixes issue #663 , i3block break

---

.local/bin/statusbar/nettraf

Here, a  function `update` is used to factor out common I/O and arithmetic. Summation is carried out by a simple _for_ loop instead of **paste**(1p).

Refactor nettraf

---

.local/bin/dmenumount

Choose available partitions to mount

dmenumount fix

---

.local/bin/statusbar/clock

since calcurse supports XDG stuff now

statusbar/clock: calcurse: use default folder

---

.config/files

add file shortcut to fontconfig

---

.local/bin/compiler

There's no stdout/stderr on this condition.

Remove unneeded std suppression

---

.local/bin/statusbar/battery

This adds backlight control of monitor through scrolling.
Requires "light" pacakage and that the user can run "sudo light" without a password, easily done through sudoers edit.
Enjoy less eye strain :)

Add backlight control as a scroll function

---

.local/share/larbs/emoji

Add new stuff, not the bloat tho

Emoji Unicode 13.0 update

---

.local/bin/dmenumountcifs

Add sudo to mkdir

---

.config/lf/lfrc

update bulkrename from b to B, added shortcut to set wallpaper from lf

update bulkrename to B, add setwallpaper shotcut

---

.local/bin/camtoggle

After I had 2 seconds of latency with this script on my machine, I decided to improve it using an article from the [Arch Wiki](https://wiki.archlinux.org/index.php/Webcam_setup#mpv)
This is another attempt of PR #765

Improved latency in camtoggle script

---

.local/bin/dmenurecord

Changed `alsa` to `pulseaudio`
Closes LukeSmithxyz/voidrice/issues/709

Fix dmenurecord breakage

---

.config/directories

I sorted them by category, so it isn't confusing, and also added `~/.local/src` & `~/.local/share`, and changed `~` for `$HOME`.

sort and add src & dt

---

.local/bin/ifinstalled

On success, output will be printed to stdout. Redirect it to /dev/null

redirect stdout to /dev/null

---

.local/bin/statusbar/kbselect

There is no need for another whole, extra package.
A simple grep filter can give the same results.

Make kbselect independent from xkblayout-state

---

.config/aliasrc

#748 
There's no stdout/stderr on this condition.

Prevent user-defined aliases/commands checking

---

.local/bin/statusbar/nettraf

I found a great tui for network traffic and such, similar in style to htop. I thought it would be a good addition.
It works with left click, not right click, that was a typo.

right clicking on nettraf now opens bmon (bandwidth monitor)

---

.config/i3/config
.config/sxhkd/sxhkdrc

Related to https://github.com/LukeSmithxyz/voidrice/pull/815

Use mw sync on F8

---

.local/bin/tag

_metaflac_ gets installed when you install flac

Added support for flac tags via metaflac

---

.local/bin/dmenuhandler
.local/bin/linkhandler
.local/bin/qndl

added flags, use qndl if possible, added options, tried to make them kinda equal.
you might want to sort line 7 of `dmenuhandler` to your liking, i just sorted the short names first and kinda grouped them.

UAE - update autisticly efficient

---

.local/bin/dmenurecord

Add a new option to `dmenurecord` to allow region video recording

Add video selection to dmenurecord

---

.local/bin/statusbar/internet

for me /sys/class/net/tun*/operstate show unknown in every state, but ./net/tun* only exists, if vpn is on

add vpn indicator to internet status modul

---

.config/lf/lfrc
.local/bin/shortcuts

Just in case someone wants to use bookmarks with lf.

Create and source bookmarks for/by lf

---

.config/shell/aliasrc

shortcutrc is created on shell directory with shortcuts script
same for zshnameddirrc

Paths fixed

---

.local/bin/td-toggle

changed "tranmission" to "transmission"

fixed typo

---

.local/bin/linkhandler

Odysee recently added RSS so I added it to linkhandler. 
https://nitter.net/OdyseeTeam/status/1411023502459736072#m

Add Odysee to Big boys club

---

.local/bin/statusbar/sb-price

e.g:
price <url> <Name of currency> <icon> <Price to show in>
price btc Bitcoin "" gbp

Change sb-price to allow custom currency

---

.config/shell/aliasrc

don't remove the whole thing, just sudo

lapsus calami

---

.local/bin/statusbar/sb-internet

show a red cross mark on statusbar if wifi is disabled/turned off.

show red cross if wifi is disabled

---

.local/bin/statusbar/sb-internet

fix https://github.com/LukeSmithxyz/voidrice/commit/dd8da1765a78117219e8b81d0945baa1e66c3a67#commitcomment-56967801

fix sb-internet problems with multiple wifi cards

---

.local/bin/statusbar/sb-nettraf

convert both $rx and $tx in one call to numfmt

---

.config/lf/lfrc
.local/bin/compiler
.local/bin/queueandnotify

replaces all appearances of "extention" with "extension"

fix "extention" typo

---

.local/bin/statusbar/sb-doppler

This lets you choose regions for Germany and get radar gifs from the national weather service instead of Sat24 which are way higher quality. This could also be usefull for people in other countries like France with Météo-France.

Regions for Germany

---

.local/bin/opout

[SILE](https://github.com/sile-typesetter/sile#readme) is a typesetting and layout engine.

add support for SILE

---

.local/bin/slider

Add `s` to OPTARGS

---

.local/bin/prompt

Delete prompt script

---

.local/bin/statusbar/sb-forecast
.local/bin/statusbar/sb-moonphase

Closes #1210
Had the logic flipped around

Fix forecast and moonphase

---

.local/bin/sd

Now sd will also work on apps like mpv and zathura

Improve sd script

---

.local/bin/statusbar/sb-forecast

The `sb-forecast` script was previously difficult to navigate due to its compact structure and terse design. This PR proposes several changes to improve the overall structure and ease of customization.
- Encapsulated logic steps into separate functions, each having a descriptive name for better understanding of the code flow
- Adopted the *snake_case* naming convention for both function names and variables for consistency and ease of reading
- Reduced the use of top-level comments in favor of step-specific comments for clarity and focused documentation
These changes will improve the readability and maintainability of the `sb-forecast` script. The modular design will also allow for easier customization.

Rewrite `sb-forecast`

---

.config/mimeapps.list
.local/share/applications/video.desktop

Updated mimeapps.list to include mp4 files.
Closes #1271

Added video.desktop file.

---

.config/newsboat/urls

Feed so you can stay updated with latest commits

Added Larbs commits RSS feed

---

.config/lf/lfrc

Reverts LukeSmithxyz/voidrice#1321

Revert "application/octet-stream is for arbitrary binary files"

---

.config/lf/scope

added support for previewing books in djvu format.

djvu files cannot be previewed

---

.local/bin/statusbar/sb-internet

From my testing the whole script now runs 1/3 faster than previously.

sb-internet: replace grep/sed commands for more efficiency

---

.local/bin/statusbar/sb-mailbox

Mirrors what also happens on Super+E

Update sb-mailbox in statusbar on closing neomutt

---

.config/lf/lfrc

#1321 had a syntax error, this commit corrects it.

Corrects "application/octet-stream is for arbitrary binary files"

---

.local/bin/maimpick

Sometimes you just need to grab some text from a video

Add OCR to maimpick

---

.config/wal/templates/zathurarc
.config/zathura/zathurarc

- Issue
- After making Zathura full screen shortcuts were not working as before
- Platform
- Debian based

shortcuts: zathura full screen mode shortcuts should work as before

---

.local/bin/statusbar/sb-bghitness

script to add brightness to the dwmblocks.

Create sb-bghitness, show brightness in the bar.

---

.config/mpd/mpd.conf

per https://wiki.archlinux.org/title/Music_Player_Daemon#Audio_configuration

Update mpd to use PipeWire

---

.config/dunst/dunstrc

https://dunst-project.org/download/#release-notes-for-v1120

Fix breaking height and preferred offset syntax in dunstrc since v1.12.0

---

.config/lf/lfrc

Quick fix for https://github.com/LukeSmithxyz/voidrice/pull/1437#issuecomment-2430008043

Improve UI for move/copy in lf
