LukeSmithxyz/voidrice

- .offlineimaprc
repository personal-local and repository personal-remote were switched so the 'remote' was the maildir section. Simple fix. :)
> .offlineimaprc issues with 'personal' config

- .config/mutt/gmailrc
Hi Luke, I used your dotfiles to get a starting point configuring Mutt, thx. I'm sending back this pull request with a minor change that would prevent a warning for those basing their config on the file on the gmailrc file.
cheers
> Stopping duplicated binding warning on NeoMutt

- .config/Scripts/screencast_pulse.sh
May I recommend adding these.
I suppose a better implementation such as getting the refresh rate of the desktop and such. I also drop frames in the encoding so the file isn't huge and has less overhead.
> fix Past duration too large

- .config/rofi/config
I already tried it on fresh installations of Arch, Artix, and Void. The three of them doesn't use the rofi configs from .Xdefaults.
(And don't worry about "Merge pull request #1 from LukeSmithxyz/master", its just me having no idea on using Git}
> Create rofi config that doesn't rely on .Xdefaults

- .scripts/i3weather
As I tried this script, I got -3-0C, which is weird, and I looked at ~/.weatherreport and got this:
```
We were unable to find your location
so we have brought you to Oymyakon,
one of the coldest permanently inhabited locales on the planet.
```
It isn't able to detect my location.
My fix requires the user to manually put their location, in which it gets suffixed to the wttr.in link. If it is left blank, (which is by default) it will still use a detected location if there's one.
I can't think of a good automated patch for it, but I'll just put this as a warning just in case others might encounter the same problem and tries to modify i3weather too.
(edited the comment because I suck on constructing sentences)
> Added location variable on i3weather script

- .scripts/extract
This is a fix to #45 where extract won't work if the filename of the compressed file has spaces.
> Quote filename to allow extracting files with spaces

- .Xdefaults
I know you're not using URxvt anymore so I think you might haven't noticed this bug. URL launching doesn't work, so I implied you just mistyped it and subtituded it with `urlview`, but it doesn't work either.
If you still remember, does this worked before? And why is it `webview` despite the program being urlview?
> Update URxvt URL launcher to use linkhandler

- .scripts/i3weather
When the `loc` variable is empty, it actually curls to wttr.in/~ and the website thinks you inputted a blank location, instead of automatically detecting your location (as of going to wttr.in/ without a location input)
I was the same user who pulled that request and haven't realized that it shouldn't have the tilde when it's empty.
I was retarded.
> Fix i3weather blank location bug

- .config/i3/lock.sh
As I use two displays, this script causes an undesirable effect, the padlock image is positioned in the middle of the screens while the green unlock thing is positioned on the center of each screen.
This update takes one separate screenshot per display connected, apply all the effects, merge the padlock image and stich them in order to have one padlock image per screen.
I'm taking the screenshots via imagemagick's import instead of scrot.
As this can be useful to someone else, i'm opening this pull request.
Sorry for my English, It's not my primary language.
> Update for multihead systems

- .config/i3/config
Just a simple QOL change since I find myself pressing ctrl+q sometimes out of habit.
> Make it impossible to accidentally kill dropdowns

- .scripts/tpb
I often forget starting the transmission-daemon when I download something via the 'tpb' script. Now the daemon is started if it was not running already.
>  tpb: start transmission-daemon if it is not running 

- .scripts/linkhandler
In the original code `exit` was executed even when the condition was not met.
> Linkhandler always exiting before case statement

- .scripts/i3weather
The connectivity check via ping is not working properly on configurations where there are multiple gateways - e.g. when using an VPN. In my case the VPN gateway(s) are not pingable, so I added `tail -1` to get the last gateway, which should be the non-VPN one <sup>I hope, cause it is like that for me.</sup>.
I also moved the `ping` before the `curl` as checking for the connection when only parsing is left seems little too suspicious :innocent: .
> Reposition ping and add failsafe tail

- .scripts/i3wifi
- With the `if-elif` structure I was getting either green or yellow since `-lt 80` gobbled up all the cases thereafter (e.g. 37 is less than 80 so the second case statement would execute)
- When signal was going up to 100% I would get a sort of dithering of my whole i3bar when it switches to and from 99%
> Fixed wifi blocklet coloring

- .bashrc
Instead of downloading the best video and audio, download audio if possible, fallback to best video and audio.
> Download either audio or video and extract audio

- .scripts/compiler
This change gives the ability to run an executable file without an extension. It just replaces your sent bit with a function called shebangtest which will test for a shebang in the first line of the file. If no shebang, then it just runs sent. I also added a few more extensions to the extension list.
> Run programs without extensions

- .config/newsboat/config
This is obviously the correct way to do it with xclip as well. I used xsel as xclip doesn't seem to play ball with my clipboard, so if xsel isn't pulled in as a dependency either add it or use xclip instead.
> replace the copy-to-clipboard hack

- .scripts/statusbar/i3internet
on my system 'grep ^w /proc/net/wireless' doesn't return a result due to
leading space being present in front of wlo1 wifi iface:
"  wlo1: 0000   55.  -55.  -256        0      0      0      0      5"
As a result the signal icon wasn't showing up. Solution is to strip it. Tested on T430s which was ok to begin with, no
regression.
> i3internet: strip leading whitespace from /proc/net/wireless output

- .scripts/i3cmds/dmenumount
This fixes #162. Other partition types which need special mount options can be added thanks to the case statement.
> add vfat support to dmenumount

- .scripts/i3cmds/displayselect
This addition allows the user to mirror the desktop across the internal and a single external display. I use this functionality for presentations, where I like to see the slides on my own display so I am turned towards the audience.
The external and internal displays use their preferred resolutions, but the internal display is scaled so that it spans the same desktop area as the external display.
> Add option to mirror displays with internal display scaling

- .scripts/i3cmds/showclip
Currently showclip doesn't work if either clipboard or primary selection is empty.
Before the change
```
echo prim | xclip -i -selection primary
echo "" | xclip -i -selection clipboard
```
shows that the clipboard is empty and doesn't show primary selection. It works correctly after swapping the variables.
> fix showclip

- .scripts/statusbar/weather
When clicking on the weather report, the output was print dirty code instead of lines. This commit fixes this error.
> Fix style when showing full weather report

- .scripts/tools/linkhandler
I searched for `TRUEBROWSER` in the repository but I did not find it in any other file. Thus, I think it should be `BROWSER`.
> Change `TRUEBROWSER` to `BROWSER` in `linkhandler`

- .config/i3/config
- .scripts/i3cmds/ddspawn
Moved scratchpad show into the i3 config file so dropdowns show right after spawning. This way there is no need to sleep in ddspawn
> Simplified ddspawn, no need for sleep

- .scripts/i3cmds/displayselect
This PR fixes scenarios where unplugged displays do not get turned off when changing selections through `displayselect`
In a scenario where `LVDS-1` and `HDMI-1` are active, if the user physically disconnect `HDMI-1` and uses `displayselect`, `HDMI-1` will not get disabled. This PR fixes this issue.
> Unplugged displays not being disabled in displayselect

- .scripts/i3cmds/maimpick
Copied a similar parameter `"$(xdotool getactivewindow)"` from the second option (a.k.a "current window") to the fifth.
---
It is quite strange why the argument for "-i" is missing in the fifth option? At least I came up with some issues which complained:
```
terminate called after throwing an instance of 'cxxopts::missing_argument_exception'
what():  Option ‘i’ is missing an argument
```
> Added window id from xdotool in mainpick.

- .profile
The last entry in this path will always have a trailing colon which can cause issues. I've tested it on a new temp user. this should do the trick.
> remove a trailing colon from the PATH

- .config/vifm/vifmrc
Better looking directory preview (in my opinion) using `tree` pacakge (0.11 MiB). `tree` output might be adjusted to your liking, e.g. different tree depth but this looked fine for most directories on my system.
Also was unable to open/edit files from within vifm which I solved by setting `vicmd=$EDITOR` but perhaps I'm missing a certain commit and you have a different solution for this.
> vifm dir preview, vicmd

- .scripts/statusbar/help
Don't know if anyone actually uses the help button in the status bar but it was pointing to the old location.
Also copied the flags over from the mod+F1 hotkey.
> point the help button to the correct file

- .scripts/tools/rotdir
`rotdir` currently uses `awk(1)` to save a list of files in a string. The use of string concatenation becomes costly proportional to the number of files to be filtered. This job is more suited to line editors like `ed(1)` and `ex(1)`.
The revised `rotdir` script uses `ed` to filter all files that match the first argument to the top of the buffer. It then prints and quits. Rudimentary error checking on the regex has been added as well.
I chose `ed` not just because it's the standard text editor, but I found that different `ex` implementations produced differing results. If you are using Arch, you will have to install a POSIX compliant `ed` --- either GNU ed or compiling a BSD one --- as it doesn't come with it by default.
> change rotdir to use ed(1)

- .scripts/statusbar/weather
My weatherreport was full with ESC and other control chars. Using the -R flag for less makes it pretty again.
> raw control chars in less, no "ESC" anymore

- .scripts/i3cmds/dmenumount
This speeds up the mounting process if you already have drives mounted
containing a large number of folders. Since 2 drives cannot be mounted in
the same folder anyway, these are now excluded from the the find
command, speeding up the mounting process.
> Prune existing mountpoints from find in dmenumount

- .config/fontconfig/fonts.conf
Avoids that `st` crashes when colored emoji fonts are installed.
These get sometimes chosen as the final fallback font for unknown glyphs.
However, `st` cannot handle colored emojis.
If `st` is still crashing, this might be caused by a user-defined override in `/etc/fonts/*`.
> Set Symbola as the fallback font for monospace fonts

- .scripts/i3cmds/ddspawn
For example, "ddspawn vifm" is generating the failing commad "st vifm -e vifm" without this fix.
This proposed change fixes this issue so that "ddspawn vifm" generates the correct "st -e vifm". It also simplify  the i3 command in my view.
Thanks for sharing this helpful script, I used it everywhere!
> Fix for spawning scripts that require no args

- .tmux.conf
`#bind-key C-a last-window # C-a C-a for last active window` didn't need renaming for me, why did you comment it out?
you uncomment it out before merging.
[more info](https://github.com/tmux/tmux/issues/1689)
> fix tmux config renames

- .local/bin/statusbar/memory
Running `free` without any modifications will result in the output being
localized into the current system-language (i.e. German if you're running a
German install of Linux). The parsing of the `memory` script however relies
on the output being in english (US).
As an easy fix we just set the system locale tempoararily to 'C' (which is the
_default_ language, i.e. english in case of `free`).
> Set system locale to international

- .config/sxhkd/sxhkdrc
The reboot bind command has been changed from `sudo -A shutdown -h now` to `sudo -A reboot`.
> Reboot bind command fix

- .local/bin/tools/linkhandler
Make it to where non-video youtube links open in `$TRUEBROWSER`, and video/playlist links open in `mpv`.
> Fix youtube handling

- .config/sxhkd/sxhkdrc
Found my keyboard volume buttons not working in larbs (archi3). At least not always, because i feel like they worked in some scenarios on fresh install. Though at that time it was hard to tell, my audio was pretty much inexistent due to the lack of pulse & alsa. Anyway, this got it working. Sorry if it's stupid, i'm very much a newb.
> Volume buttons support

- .local/bin/i3cmds/dmenurecord
When attempting to run dmenurecord for screnacast or video it kinda dies silently with :
```
Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x5558eb7d5240] Cannot open display :0.0, error 1.
:0.0: Input/output error
```
>  Attempting to fix 'Cannot open display :0.0' 

- .config/sxhkd/sxhkdrc
This reverts commit 6d136d4fdd9f9a3c24e278cb9d863a6ea61ebbba.
Volume and other media keys were added in d4bcaf9de80d27f0c4bd5f4d96f1eb546783feda using lmc tool that updates the i3blocks volume module
removing this to avoid conflict and unnecessary bindings
> Revert "Volume buttons support (#334)"

- .local/bin/linkhandler
I do not understand why this is the case but removing the double quotes from the `$BROWSER` argument to successfully open.
> setsid cant open $BROWSER with double quotes

- .config/newsboat/config
This was fixed for the `archi3` branch in dcd68da.
> Fix typo in newsboat config

- .local/bin/statusbar/torrent
Eliminate the newline so the torrent icon will show in the latest i3blocks.
> Fix i3blocks torrent icon

- .config/newsboat/config
- .config/nvim/init.vim
removed duplicate keybinding in newsboad for next-unread command
added a command to install plugins on first run
added a command to write the nvim file buffer as sudo on files that require root privileges with the w!! command
> fix to newsboat config and additions to init.vim

- .local/bin/statusbar/battery
Newline after the </span> tag so it'll work in the latest version of i3.
> Fix for i3 status bar battery indicator

- .local/bin/dwmbar
Semantic changes to the `dwmbar` output
* Muted icon when output is muted
* Icon now displays on the left of the icon, matching other bar elements
* Stereo speakers do not cause 2 sets of icons
* If output is muted, only the mute icon is displayed
* Removed colon from the `mw` output 
My `amixer get Master` command returns a Front Left and Front Right, presumably due to stereo, this meant that I had duplicated output information in the bar. While fixing this could be done trivially with by piping into `head -n 2` I wanted to reverse the icon and volume so it matches other elements on the bar (and looks like the i3 status) which can be achieved with `tac`. Although this still leaves the volume number when you have your output muted.
To remedy this, the line can be flattened in order to use …
> dwmbar changes to icon layout 

- .config/sxhkd/sxhkdrc
The increase volume gets added by 15 ignoring the shift. Changing this works again.
> fix on increase volume

- .config/ranger/commands.py
`fzf_bring` currently has the [same functionality](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/ranger/commands.py#L139-L142) as [`fzf_select`](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/ranger/commands.py#L87-L90).
I removed that and replaced it with what I could understand is its functionality, to move the file selected with `fzf` to the current dir:
`shutil.move(fzf_file, self.fm.thisdir.path)`
There were a few duplicate imports in `commands.py` that weren't needed, I removed those as well.
> ranger: fix fzf_bring to not be a duplicate of fzf_select

- .local/bin/compiler
The `rmarkdown::` portion makes sure that no other functions mask render, and its calling it from the required **rmarkdown** package, and the addition of the quiet portion isnt redundant with the `R -q` flag, i tested script and in Vim it reduces how much text and verbose messaging comes from pandoc at the bottom to about 3 lines.
> Improve and more efficient RMarkdown Compilation

- .config/i3/config
- .config/mpd/mpd.conf
- .config/nvim/init.vim
- .config/ranger/rc.conf
- .config/sxhkd/sxhkdrc
removed double keybindings between i3 config and sxhkd, and non existent script keybindings from i3 config
moved samedir keybinding to sxhkd so that it can be used on any wm
changed output of mpd.conf to alsa since LARBS now comes with alsa only
fixed class of Vimwikiindex
changed rangers rc.conf to use atool for archive extraction instead of extract script (which seems to be non existent or renamed)
added a nice vimdiff highlighting setting to init.vim so that lines that are changed are highlighted, but the text is actually readable as it now stands out in the line
> some small updates

- .config/i3/config
Removed redundant keyboard shortcut that can be found in the sxhkdrc config
> fix(i3 config)

- .config/i3/config
The `lmc` script was removed in 2e2200b4b96436fbfee59c74bfeb9f7e417a84df, but there still exist references to it in the i3 config. This pull request resolves #459.
I have yet to test for bugs since I don't use ALSA.
> Remove lmc references in i3 config

- .xprofile
The `.xprofile` file currently uses an absolute path for the LARBS picture in the `notify-send` command, which obviously won't work unless your name is Luke. This pull request will fix this issue.
> Replace absolute path in .xprofile

- .config/i3/config
In #460 I attempted to replace the `lmc` references with `alsa` and `pkill` commands, but I used the wrong syntax when combining these two. Because of this, none of those keybindings work currently. My bad.
This pull request fixes #470.
> Fix i3 audio keybindings

- .tmux.conf
I noticed there was no bind to create a new window in tmux
Edit: The default to open a new window is `Prefix + c` but that is assigned to `split-window -v`. Also `Prefix + C-c` is for a new session by default so I guess `Prefix + C-n` could also be a good candidate
> tmux bind for new window

- .config/i3/config
Default inner and outer gaps can now be changed in one place instead of changing the initialization and the shortcut to reset gaps to default.
> Added variables for default inner and outer gaps.

- .local/bin/torwrap
referencing issue #512 
this would implement the newer, continued python3 version
> tramsmission-remote-cli discontinued, using python3 fork tremc

- .config/user-dirs.dirs
calcurse keeps creating new configs at ~/ without these two lines
> for partial XDG supporting apps

- .profile
Not every program will read them from ~/.config/user-dirs.dirs so might as well export them yourself... Also can now use them elsewhere.
> Update .profile to export XDG base dirs

- .config/sxiv/exec/key-handler
Running `C-x c` `copy` or `C-x m` `move` will copy/move all the marked files to a
single location. If that location is not a directory, then creating that file
and overwriting it several times results in complete loss of data in the case of
moving, and unhelpful behaviour in the case of "copying". Only the last marked
file remains in the file.
This fix only moves/copies the first marked file, then issues a warning message.
(My StumpWM gentoo linux system, and a Brazilian cat)
P.S. Send me pictures of your cat if reading this, thank you.
> sxiv: Prevent writing all marked imgs onto file (lossage)

- .cache/bg
- .local/bin/setbg
- .local/share/bg
often the ~/.cache directory is deleted because it gets too big, in my case if i compile stuff with yay, firefoxs cache also gets quite big, and mesa shaders are also stored there.
> Move bg link to ~/.local/share/

- .config/aliasrc
- .config/zsh/.zshrc
- .local/bin/shortcuts
I think this is useful. It uses the same directory shortcut file (~/.config/directories)
You can do things like this from Zsh shell:
`$ mv file.tex ~d`
Or even better and more relevant example:
`$ rsync ~d/file.tex ~D/project.tar user@server:~/`
The main idea is the user doesn't have to write the entire path when using Zsh shell only.
They can use any binding from the directory shortcut file.
Filename completion works too when using this.
> New feature: Zsh named dirs

- .config/nvim/init.vim
I found a way to still set defaults for init.vim when [original method](538) did not work properly.
> fix: Use default if $XDG_CONFIG_HOME is not set

- .gitmodules
Use HTTPS instead of SSH, so that users without a GitHub account can still clone the submodule.
> fix: Use HTTPS instead of SSH

- .config/ranger/rc.conf
By default, `ranger` supports `$XDG_CONFIG_HOME` and also provides fallback if not set. Thus the default path for `scope.sh` is in accordance with **LARBS** and setting `preview_script` explicitly is unnecessary.
To properly use `$XDG_CONFIG_HOME` though for `ranger` when sourcing additional files, a workaround is needed, using `fm.confpath()`.
Fixes #552.
> fix: Properly evaluate $XDG_CONFIG_HOME in rc.conf

- .config/lf/lfrc
Need to send the commands in shell scope to `lf` in order to use environmental variables in `lfrc` file. We can utilize this method to use `$XDG_CONFIG_HOME` to set path to `scope`.
> chore: Use $XDG_CONFIG_HOME in lfrc

- .config/xprofile
- .profile
Just this one change for now, but there's a couple more that I can add if you're interested in upstreaming them:
* (in `~/.config/files`) alias cfp -> `~/.profile`
* (in `xprofile`) set an environment variable to make touchscreen input work correctly on Firefox and Firefox-based browsers
> tell Qt to use whatever the current GTK2 theme is

- .profile
go folder is the go language workspace and is placed in your home directory by default. even if you don't use go, it will be created in process of building something written in go. this moves go folder to .local/share/go.
i'm not writing in go, maybe there is a point of keeping this folder in your home directory, but i don't really see it.
> hide go folder

- .local/bin/compiler
`library::` is all you need to load a library before using one of its functions.
> remove unneeded require

- .config/i3/config
it could only work with '&&' and only in this order. i see that it would be logical to "slock" even if a preceding command will fail, though like i said it would only run in this order. i've tried using a script (even in this order) with " ; " it would not run. 
the audios would mute and the screen would turn off, but it would not lock.
> i3 to use slock

- .local/bin/dmenumount
- .local/bin/dmenuumount
Commit 6de12bf fixes #440. Some symbols were unnecessarily escaped and caused `find` to fail, so you were unable to pick a mount point. (dmenu was empty)
Commit 51599d0 removes type restriction from `lsblk` output. Not sure why it was here but my pendrives get listed as just drives. I can mount and use them normally thought, so I just removed the restriction. If there was a good reason to have it that way I'll revert it.
Commit 07ceeeb makes it possible to exit the command in the middle with escape key. When testing if my pendrives get listed after I got the initial selection of mount drive I pressed ESC, but I still got askpass prompt. Now when you press escape the program ends, and doesn't continue with empty variables.
If I changed too much just let me know, so I can change/revert some …
> dmenumount fix + improvements

- .config/nvim/init.vim
The default location in home directory.
Now placing it on nvim data directory(~/.local/share/nvim) or "~/.vim" directory in case of the good old vim.
> Placing NERDTree bookmark file not on home dir

- .local/bin/displayselect
- .local/bin/statusbar/music
- .local/bin/statusbar/nettraf
- .local/bin/statusbar/torrent
- .zprofile
The `paste(1)` command is designed to concatenate lines of input. Several scripts used something like `tr '\n' '+' | sed 's/+$//'`. I've replaced this with a much simpler `paste -sd '+'`.
> Replace tr(1)/sed(1) combo with paste(1)

- .local/bin/statusbar/moonphase
As described in issue #636  using wttr.in was incorerct by 16%
Now the `~/.local/share/moonphase` looks ugly, so dont look at it.
> Now moonphase is correct and even more precise

- .config/zsh/.zshrc
When using tab completion in zsh, it can get annoying to type capital letters for directories.
This fix allows for case-insensitive completion, e.g. `/etc/x => tab` will also include `X11` in the options menu.
> Add case-insensitive autocompletion to zsh

- .local/bin/shortcuts
This new feature is aligned with #540.
It only adds one line of code.
Here you can do thigs like:
```
$ v ~cfp  # I know we have an alias for this simply: "cfp"
```
But more appropriately you can do:
```
$ git log --graph -p -- ~cfp
$ git diff <local_repo_copy_path>/.config/.profile ~cfp
```
This adds value, I guess.
This is still called Zsh named **dir** in Zsh docs so I've used the same file;  It simplifies things too.
> Zsh named (sic: files) directory

- .local/share/applications/img.desktop
Would previously error out as such:
```
Opening "<file>" with Image viewer  (image/jpeg)
sxiv: file://<filepath>
sxiv: No valid image file given, aborting
```
> Fix sxiv .desktop file

- .local/bin/booksplit
I used your script but on an album with 8 tracks, and the last one ended up not having a leading zero like the rest. This should fix it.
> adds 2 digits for last track for cases when less than 10 tracks

- .local/bin/dmenumountcifs
> mount NAS shared folders

- .config/newsboat/config
the `;` must be surrounded with space, or you wont be able to open stuff
> newsbloat 2.20 compliant

- .local/bin/statusbar/kbselect
Works on any init system.
Requirements: dmenu, xorg-setxkbmap, xkblayout-state (https://github.com/nonpop/xkblayout-state)
Add this line to Luke's dwmblocks
{"",	"kbselect",	0,	30},
> keyboard layout switch

- .local/bin/statusbar/battery
The current battery script works well on my laptop (that has a battery) but on my desktop (that lacks a battery), it floods my logs with the following because `cat` keeps throwing an error each time the script is run.
```cat: '/sys/class/power_supply/BAT?/capacity': No such file or directory```
This fix breaks the loop if the file doesn't exist before it's being read with `cat`, thus preventing any errors from reading a file not existing.
> Prevent error when having no battery

- .local/bin/statusbar/nettraf
Convert network speed into human-readable format using numfmt, this will handle low and high values properly.
> improve speed format

- .local/bin/statusbar/cpubars
This script shows CPU load 
I kinda missed this feature since migrating from i3/polybar, so I decided to implement it.
> Add cpubars script for dwmblocks

- .local/bin/linkhandler
"$EDITOR $1" caused a 'file does not exist' error in Alacritty terminal, despite passing the conditional if statement preceding it. Splitting the quotes into "$EDITOR" "$1" fixed the issue. Not sure why.
> linkhandler: Fix file opening in $EDITOR for Alacritty terminal

- .local/bin/compiler
Adding `[ -x ]` also checks if the command is an executable; if this
check is skipped, then user-defined aliases will interfere and validate
the condition (unintended).
> Prevent user-defined aliases/commands checking

- .config/newsboat/config
Adds macro to newsboat to view youtube comments from command line. Requires youtube-viewer.
> Add macro to view youtube comments

- .local/bin/dmenurecord
Seems that @drakenewell will need to provide more details about his issue.
Someone commented that it broke for them which somewhat makes sense because alsa is lower level and might as well use it.
> Revert changes to dmenurecord

- .config/tmux/tmux.conf
Following https://github.com/LukeSmithxyz/voidrice/issues/800
It was added a configuration to reduce the escape timeout to a lower value in `tmux.conf`.
> Reduce escape delay time in tmux

- .local/bin/linkhandler
since mpv can handle peertube videos, it would be best to open video links in e. g. newsboat with mpv.
> add videos.lukesmith.xyz to linkhandler script

- .local/bin/rotdir
Now doesn't interpret file name as regex pattern.
Since variable expansion is no longer needed, I single-quoted the whole thing and removed escaping backslashes.
> Improve rotdir script

- .local/bin/ext
This is a re-attempt of #643 
- `[ "$archive" = "" ]` may be replaced with `[ -z "$archive" ]`
- added exit codes
- upon entering `ext -c` with no arguments stderr will be thrown
from readlink, should be suppressed
> Exit codes, stderr suppression, minor edits

- .local/bin/dmenumount
Exfat does not support user permissions. So using chown on a file inside exfat will always fail.
> mount exfat for rw

- .local/bin/shortcuts
This is needed on the ranger and similar programs as it can't expand shell vars directly similar to shells.
Without it, the key combination "gd" will not work on the ranger and similar problems.
> Expanding shell vars before passing to the files to help ranger and other similar programs

- .local/bin/sysact
- .zprofile
On systems with multiple users running multiple sessions, it's useful to only kill the current user's Xorg and dwm sessions. This enables simultaneous logins on a single system and kill requests only point at the user's processes.
> kill and start only current user's session

- .local/bin/cron/checkup
The value of the "-c" parameter was missing, so the check for an active internet connection as well as the whole script failed.
> Add missing value for parameter

- .local/bin/compiler
I know @LukeSmithxyz  doesn't really use emacs, but lots of people do, and this compiler script is just missing this one common format...
(coming from a doom-emacs user)
> Add support for Org-Mode files.

- .local/bin/compiler
Pandoc is **not** an option for org-modes (#837) since org files are rarely "pure" and often rely on emacs configs or other packages.
Above that many org files use emacs environmental functions/variables that need to be evaluated before compilation.
That being said a xelatex user have his `org-latex-compiler` set to `"xelatex"` so there is no point in including that in the command as well.
Or if the org author sees fit can include that variable in the org file (in the very crucial part that is ignored by pandoc).
> Use Emacs to compile org files

- .local/bin/sysact
Run slock and pass the command as the argument, which means the system will be
locked on resume.
`-i` is required for this to work, which works fine on my system however I have
`NOPASSWD: ALL` in sudoers.
> Add screenlock to suspend/hibernate

- .local/bin/statusbar/popupgrade
Fixes #847 
> since the variable is not being used again, "_" wil suffice, "line" as the name would also be valid.
Graphical explanation:
> read command fix

- .config/shell/profile
- .local/bin/displayselect
- .local/bin/statusbar/music
- .local/bin/statusbar/torrent
According to FreeBSD's [paste(1)](https://www.freebsd.org/cgi/man.cgi?query=paste&sektion=1&manpath=FreeBSD+12.2-RELEASE+and+Ports), the extra `-` is needed (tested by myself).
This obviously works for Linux as well, tested on Void Linux at least.
> Create a colon-separated list of directories named bin, suitable for use in the PATH environment variable:
`find / -name bin -type d | paste -s -d : -`
> Compatibility for FreeBSD's paste(1)

- .local/bin/compiler
Tested it on a project with this structure:
```
- root
|- test
| - Test.java
```
The user must call `compiler` from the root of the project, but that should not
be an inconvenience because usually the working directory is the project's
root. Nonetheless, it also works for java files in the current working directory,
in case someone just wants to test some code quickly.
> Added Java support for compiler script

- .local/bin/displayselect
Using displayselect to select a single external display connected via display port (nb: you won't be able to recreate with a DP->HDMI converter, only DP->Monitor) will result in nothing happening. This is because the primary display is given in xrandr as eDP1, and the external display port as DP1.
> Fixed edp1 botching dp1 grep

- .local/bin/statusbar/battery
Instead of having sed check for every state, I used a case statement. Also, I abstracted the format aspect of it to its own function. When doing something like `time( for s in $(seq 10000); do; battery; done )` for this, it seems to be way more effecient with the case statement.
> Case block and function is more effecient

- .local/bin/statusbar/sb-music
- .local/bin/statusbar/sb-pacpackages
The 2619a88fcd94cbd4b2caa719ba926ae0013fb4ec update might have broken scripts, like this, that use a script from `~sc/statusbar/`
> adopting `sb-`

- .local/bin/shortcuts
This feature was introduced in #639.
It might have forgotten during cleaning or refactoring.
> Restoring feature for zsh file shortcuts

- .config/shell/profile
Find is faster and it is only one command. The last `:` is removed by the parameter expansion (works in both Bash and Zsh).
> Use find instead du for more efficient execution.

- .config/nvim/init.vim
While removing trailing newlines is a good idea, it is a problem when
editing C files which "must" have an empty line at the bottom.
Tested a .c and non-.c file.
Works by deleting all the lines then adding just one to C programs.
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf
5.1.1.2 #2
A source file that is not empty shall end in a new-line
character,which
shall not be immediately preceded by a backslash character before
any such splicing takes place.
> Leave a single newline if reducing trailing (C files)

- .local/bin/statusbar/sb-tasks
I think it is not necessary to store the output of tsp in a temporary file. 
All necessary operations can be performed during runtime.
> Prevent unnecessary caching of tsp output

- .config/newsboat/urls
There is no reason for the URL of Luke's main RSS feed to be transferred over unencrypted HTTP. That's why i changed it to HTTPS. Nothing big, it just mildly infuriated me.
> Encrypted connection to Luke's RSS feed

- .local/bin/statusbar/sb-forecast
The source of problems is the `+` sign. It wont allow to sort numbers how we like.
----
Lets say we have these:
```bash
echo "m1\nm9\nm10\nm11\nm+99\nm+100\nm+101\nm-1\nm-9\nm-10\nm-11"
```
What we **want** as end result  is :
```
m-11
m-10
m-9
m-1
m1
m9
m10
m11
m99
m100
m101
```
Because we will sed out the first (coldest) and last (hotest) line.
Though what we will get without using `sed 's/+//g'` before the sort command in the pipe, is this:
```
m-11
m-10
m-9
m-1
m+100
m+101
m+99
m1
m9
m10
m11
```
The numbers which had a `+` are sorted before, so putting them in the middle.
> fix sb-forecast

- .config/shell/profile
- .xinitrc
A custom filename and directory can be specified with startx command,
which in this case is $XINITRC variable that indicates
$XDG_CONFIG_HOME/x11/xinitrc
I realized there was already and $XINITRC variable that is commented out, I don't know if what I am suggesting was done before and decided it was not preferable for some reason. But I am making the pull request anyway in case it is useful.
> Deleted the .xinitrc link at $HOME for even a cleaner home directory.

- .config/zathura/zathurarc
Since no other key binding starts with g, it makes more sense to use g instead of gg to go to the first page. This change also allows the use of ng to go to the nth page (instead of nG or ngg).
> Use g instead of gg in zathura

- .local/bin/statusbar/sb-price
Is: `less` outputs the raw ascii of the $chartfile, which includes escape characters to change output colors. This does not resemble a graph. 
Should be: Adding -n flag to have `less` create colored output properly.
> Handle color control sequences

- .local/bin/slider
I set free-sans to be the default, because it seems that that is what imagemagick is uses, when you don't specify a font.
> make it possible to change the font for text slides

- .local/bin/rssadd
Before this, rssadd only accepted a URL as argument. Now, if given
an xml file, it will parse it and extract the proper url. This lets it
be used in conjunction with firefox for quickly adding RSS feeds (as
firefox would give it the file rather than its origin URL). This works
on a majority of RSS feeds, but fails on some that miss the proper link
tags. The original behaviour is still mantained alongside the new.
> `rssadd` improvement: additionally extract from xml files, not just urls

- .local/bin/sysact
If you don't specify it, it won't work:
$ sudo -A openrc-shutdown -p
* openrc-shutdown: No shutdown time specified
> Specified shutdown time (0 seconds) for openrc shutdown option

- .config/newsboat/config
Fixes #921. Previously, the `,c` macro would not work for users with `dash` as `/bin/sh`.
> newsboat: fix non-posix here-string for clipboard macro

- .local/bin/statusbar/sb-music
On many of the machines that I install the rice, users have external storages for storing their music. When not attached, it usually leaves an ugly error message in the statusbar (`ERROR: Failed to decode /home/user/Music/path/...`).
It seems this extra sed command prevents it.
> Suppress sb-music errors

- .local/bin/dmenumount
Replace explicit empty string check condition with inbuilt POSIX compliant empty string check flag, in adherence with the rest of the script.
> Update: dmenumount -Make empty string check more consistent

- .local/bin/sysact
Deprecate backticks, include `eval` to clarify execution, and quote to prevent word splitting.
> deprecate backticks

- .local/bin/tutorialvids
In light of the current YouTube channel situation  (https://lukesmith.xyz/articles/deletion.html), I have changed all YouTube links from the `tutorialvids` script to use their PeerTube equivalents.
Opening PeerTube video links from `mpv` is a bit slower than YouTube or Odysee links, but I suppose that's the price one pays for not relying on third party platforms.
> Change tutorialvids links to PeerTube due to potential YT deletion

- .config/fontconfig/fonts.conf
Some programs like `gotop` [1] or `bottom` / `btm` [2] weren't displaying properly in `st` (though e.g. `alacritty` worked by default, and I tried switching, but that's just not gonna happen:D), and I was able to fix the glyphs with the Braille font (don't recall where I found the recommendation, perhaps [3]).
needs `ttf-ubraille` [4] so an update in LARBS progs.csv would be needed aswell.
Don't forget to 
```sh
fc-cache -fv --really-force
```
Also beware of stuff like [5].
[1] https://aur.archlinux.org/packages/gotop
[2] https://aur.archlinux.org/packages/bottom-bin
[3] https://github.com/kovidgoyal/kitty/issues/1623, https://github.com/cjbassi/gotop/issues/18#issuecomment-637271051 and others
[4] https://aur.archlinux.org/packages/ttf-ubraille
[5] …
> Add `Braille` font family to `monospace` @ fontconfig

- pinentry/preexec
thanks to the `pinentry` package, it uses gtk2 auth. box, or if you don't have gtk2, uses cli/curses box, **in the background**, so it makes passmenu, unusable.
The file originates from `/etc/pinentry/preexec`.
> for passmenu to use gtk3 box

- .local/bin/dmenurecord
You can just use `awk '/thing/ {print ...}'` instead of `grep thing | awk '{print ...}'`, you probably already know this but haven't noticed this yet in this script.
> use just awk without grep

- .local/bin/peertubetorrent
The script stopped working because the URL format changed, this fixes it.
> Update peertubetorrent due to changed URL format

- .config/nvim/init.vim
github automatically redirects to vim-airline, so this is not a
problem when installing, but updating just for the sake of
explicitness and having the correct username/repo
to verify here's the vim-airline link https://github.com/vim-airline/vim-airline
> vim-airline repo changed its ownership from bling to vim-airline

- .local/bin/dmenuumount
people who have installed their system in EFI may accidentally unmount their boot partition, thus creating problems when upgrading their system's kernel.
> add `/efi` to exceptions in dmenuunmount script

- .local/bin/ext
Arch & Artix already have the `libarchive` pkg, which contains `bsdtar` (can't even uninstall it).
So lets just use it, since its already there, superior, faster, it also has easier syntax, and it auto-detects the compression.
<details>
<summary> btw the .tar.zst was wrong anyhow, so if u wont merge this, dont forget to fix that. from the manual: </summary>
```
-I, --use-compress-program=COMMAND
Filter data through COMMAND.  It must accept the -d option, for decompression.  The argument can contain command line options.
...
...
--zstd Filter the archive through zstd(1).
```
dont use `-I zstd`, just use `--zstd`. __i think__.
</details>
> update `ext` script

- .local/bin/statusbar/sb-popupgrade
In [https://github.com/LukeSmithxyz/LARBS/commit/b4167af0e79dab3a618059438a371fc733562978](url) the default AUR helper was changed from paru to yay. The sb-popupgrade script should also have this change.
> Changed paru to yay due to new LARBS changes

- .config/mpv/scripts/modules.lua
- .gitmodules
fixes https://github.com/LukeSmithxyz/LARBS/issues/326 and https://github.com/wis/mpvSockets/issues/5
The error message is cryptic but I figured out it is caused by mpv trying to read and parse everything in the scripts directory as script files and failing to do so for the mpvSockets directory inside it.
> mpv: fix error on launch by removing directories inside mpv's scripts directory

- .local/bin/dmenuumount
If a partition doesn't have a label, it results in a double space that awk ignores. Which is why the changes include a pipe into sed.
> Add partition label to dmenuumount script

- .local/bin/torwrap
This can be known from "ifinstalled" code
Otherwise, it results in error and reports that "tremc-git" must be installed even though it's installed already.
> Here program name should be given not package name

- .config/wal/postrun
- .local/bin/displayselect
- .local/bin/samedir
- .local/bin/setbg
- Wal: store dunst and zathura configuration files in variables for neatness.
- samedir: Just use setsid instead (or is other functionality needed?)
> General script improvements

- .config/lf/lfrc
fix bug in lf where symlinked files don't open in the expected program
> follow symlinks when detecting filetype in lf

- .config/nvim/init.vim
After saving a file with some trailing white space, your cursor will be set at the line with the trailing white space instead of your initial one.
> Resets cursor position on file save (Issue #1040)

- .local/bin/dmenuhandler
Case sensitivity prevents dmenuhandler from copying the URL to the clipboard.
> Fix case-matching

- .config/nvim/init.vim
changed path to `.config` instead of `~` to avoid a messy `~`. Also added a carriage return to the `VimwikiIndex` map.
> vimwiki chages

- .config/nvim/init.vim
Vimwiki is not config but it's data so ".local/share/nvim" is
more proper location for it.
Here relative path was given so it tries to create new vimwiki
folder when launched from other than home dir or changing current
dir using `:cd <path>` inside vim when launching vimwiki.
> Move to data folder and need absolute path here

- .local/bin/setbg
path should be "$HOME/.local/share" (there's an extra slash)
> remove typo in bgloc

- .config/nvim/init.vim
- .local/bin/shortcuts
This will allow using the mappings in the vim command line.
Here the leader is ";"
So here `:e ;cfz` typed fast will expand into
`:e /home/user/.config/zsh/.zshrc`.
This is more helpful with :sp, :vs, :cd or anywhere where a file or
a directory is expected in the vim command line.
> Shortcuts in vim command line from bm-dirs/files

- .local/share/applications/file.desktop
'file.desktop' uses `lf` instead of the wrapper script `lfub`
> file.desktop: Use `lfub` instead of plain `lf`

- .local/bin/remaps
Uses the `altwin:menu` option from setxkbmap to map the menu key to right super instead of xmodmap, which is deprecated. setxkbmap's options can be viewed with `man xkeyboard-config`. Also tried to make the comment for the xset rate change more helpful.
>  remove xmodmap from remaps script

- .config/lf/scope
fallback to using mediainfo when ffmpegthumbnailer or pdftoppm is not available.
correct terminal width for bat.
use cut instead of awk for efficiency.
improve spacing/indentation for the sake of consistency in code.
> Numerous improvements to scope

- .local/bin/peertubetorrent
Because of https://github.com/Chocobozzz/PeerTube/pull/3746, the torrent URL is now different from the normal video url. This means the peertube API is needed to get the new torrent link.
> Fixed peertubetorrent

- .local/bin/dmenuhandler
- .local/bin/peertubetorrent
- .local/bin/statusbar/sb-clock
removes the need for `/` to be escaped with a backslash
> use `|` as sed delimiter if pattern has `/`

- .local/bin/maimpick
**Before**:
**After**:
Please read the commit for extra details.
---
This just makes the script easier to read and avoid repetition.
---
Excuse the tab-space formatting, it got in the way unfortunately; I can re-commit if it's a bother.
> Screenshot utility improvements (maimpick)

- .config/lf/lfrc
Without double quotes, fzf-select fails when selecting a file whose path contains whitespace. 
If I recall correctly, it will raise the error "select: required an argument".
> Fix fzf select in lf

- .local/bin/samedir
samedir didn't work properly when the shell was opened inside lf using the w keybinding, now its fixed.
> fix bug in samedir script

- .local/bin/linkhandler
When passing the -c option, linkhandler reads from the clipboard. It's very useful if you have it bound as a macro, as you can copy a link in a browser, and can very easily open the copied url in a better application.
> Give linkhandler option to read from clipboard

- .local/bin/dmenumount
If a partition doesn't have a label, it results in a double space that awk ignores. Which is why the changes include a pipe into sed.
> Add partition labelling to dmenumount

- .config/pipewire/pipewire.conf
pipewire-media-session is now in conflict with wireplumber, which is needed for pipewire-jack and pipewire-pulse. Amend pipewire config to use wireplumber instead.
> Change pipewire-media-session to wireplumber

- .config/pipewire/pipewire.conf
As we see in the docs here: https://pipewire.pages.freedesktop.org/wireplumber/running-wireplumber-daemon.html#pipewire-conf we need to start wireplumber in replace of the old media session, not "wireplumber as server". (This is my first hecking commit ever !!!!!!!!!)
> fix wireplumber

- .config/nvim/init.vim
Doing things in a way that was originally intended. This also makes it easier to copy the autocmd to a lua based configuration.
> Standardized passing of filenames to shell scripts

- .config/nvim/init.vim
Sorry for making another pull request here, but I realized that the command would fail if the filepath contained spaces. Adding quotation marks fixes this issue
> Fix bug with spaces in directory names

- .local/bin/texclear
Add double quotes to prevent splitting directory names with spaces
> Texclear fix for directories with spaces

- .local/bin/compiler
Allows parsing texroot comments so that you can compile a LaTeX document from outside of the document root, as long as it contains the usual magic comment format:
% !TEX root = doc.tex
> Parse tex root for more complex latex projects

- .config/newsboat/config
The _--restrict-filenames_ parameter will automatically replace spaces with underlines.
> remove spacing from saved audio for tsp/newsboat

- .local/bin/dmenuhandler
the title then extension format with the --restrict-filenames again for underscores instead of spaces. Works typically well as music will have Artist name first usually followed by song title so no need to format.
haven't looked into the --embed-metadata parameter, only imagine it could be useful if it saves the url suffix for youtube link (which you don't want in your filename hopefully)
for my video downloads, i just use this.
alias ydl='yt-dlp -o '%(title)s.%(ext)s' -f bv+ba/b --restrict-filenames' alias mp3='yt-dlp -o '%(title)s.%(ext)s' -f bestaudio -x --audio-format mp3 --embed-thumbnail --restrict-filenames'
Probably bad practice to have single quotes within more single quotes but ran into issues with yt-dlp over using double quotes.  
-Ryan
> underscore vs spaces, and naming convention

- .local/bin/otp
Make a temporary directory in `$XDG_RUNTIME_DIR` instead of `$PASSWORD_STORE_DIR`. 
`$XDG_RUNTIME_DIR` defaults to `/run/user/$uid/`. This directory has the security advantage of only being readable and writable by the current user and being mounted in RAM, causing the screenshot to be fully wiped on shutdown and not needing shred, which doesn't work reliably on SSD's. 
Also quoted `$dir`, for the off chance someone has spaces in their `$PASSWORD_STORE_DIR`.
Removed the check for `xclip` and the `$issuer` and `$name` variables, as they are unused.
If you're wondering why echo is piped into dmenu, on my system dmenu hung when called without the pipe, causing the whole script to freeze.
> Make otp script more secure + other improvements

- .local/bin/tag
When you don't manually specify $total and $date with an mp3 file the eyeD3 command tries tagging with an empty variable, which causes it to error. This fixes it by only passing the parameter to the command if the variable is set. 
This pull request also adds support for the $genre and $comment variable.
> Fix tag script mp3 issue

- .local/bin/tag
eyeD3 got orphaned in the AUR, so I looked for an alternative. Apparently ffmpeg also supports the ability to tag audio files, so this pull request replaces all the helper applications with ffmpeg
> Use ffmpeg for tag script

- .local/bin/statusbar/sb-forecast
- .local/bin/statusbar/sb-moonphase
Sometimes curl doesn't error, but downloads an empty file instead and still updates the date, causing the rest of the script to fail and not showing the icons on the statusbar. This checks if the downloaded file is not empty before checking if the date is good.
> Make sb-forecast and sb-moonphase more robust

- .local/bin/statusbar/sb-doppler
Sioux Falls is in South Dakota, not Iowa
> Fix Sioux Falls

- .local/bin/sd
Now sd script can open a terminal window in the same directory as the currently active lf file manager window
> Make sd script work with lf file manager too

- .config/lf/lfrc
- .config/zsh/.zshrc
I was annoyed by the fact that once I close `lfcd`, I could not longer press `Ctrl+C` to interrupt commands. This PR untraps the signals once `lfcd` quit.
> Stop trapping SIGINT to allow further use of Ctrl+C once lfcd is closed

- .config/lf/lfrc
Prevent file paths containing space characters to be passed to `mimeopen` as a vector of incorrect paths.
> Avoid expansion of file path containing spaces

- .config/lf/scope
Fix epub preview not working which has MIME-type `application/epub+zip`. The script match pattern `application/*zip` first, instead of previewing the image.
> fix epub preview not working

- .local/bin/compiler
Output file is empty without `-T pdf` flag.
> Fix markdown compiling

- .local/bin/sd
* Programs that show ~/ or / instead of the actual working directory are now ignored by the script (except for zsh & lf where its correct). This will fix bugs where sd opens your home folder instead of the current working directory.
* This also removes the need for manually excluding all programs that don't show the correct cwd.
* git (and its sub-processes) will show the root of a repository instead of the actual cwd, so they're ignored too.
> Various bug fixes and improvements for sd script

- .config/shell/profile
used in programs like `xtrace` (line 172 `/usr/bin/xtrace`)
> add TERMINAL_PROG variable

- .local/bin/statusbar/sb-kbselect
If we don't check and user presses escape in dmenu it will print nothing.
> Check if user hasn't selected anything in keyboard layout switch script

- .local/bin/mounter
If no decrypted LUKS drives are found, the script errors with `ls: cannot access '/dev/disk/by-id/dm-uuid-CRYPT-LUKS2-*': No such file or directory` and stops, this makes sure the error doesn't stop the script.
> Don't stop mounter script on ls error

- .config/nvim/init.vim
`eol`or `endofline` is set on by default in vim so there is no need for this. fixes #1256
> remove adding newline

- .config/firefox/larbs.js
- .config/lf/icons
- .local/bin/statusbar/sb-doppler
Mousebros...
This issue might disappear over time as more packages are installed, but i had this issue when i first installed LARBS and this fixed it.
Also mentioned in the  [arch wiki](https://wiki.archlinux.org/title/firefox#Right_mouse_button_instantly_clicks_the_first_option_in_window_managers
)
_Duplicate because the other was deleted due to cleaning up my github gits_
> Fix mouse issue in firefox, add avif icon and add DK & SE to dopplar

- .config/x11/xprofile
- .local/bin/remapd
This PR would make remaps be run automatically when a new keyboard is plugged in. Note that if the script will be run unprivileged, you will have to add `kernel.dmesg_restrict = 0` to /etc/sysctl or to a file in /etc/sysctl.d. This allows unprivileged reading of dmesg which probably fits the threat model of the majority of desktop users.
`dmesg -W -f kern | grep "input:" -q` blocks until dmesg writes a line containing "input:", which happens when a keyboard is plugged in. I'm sure you could refine this grep statement, but I left it as general as possible.
> Automate remaps upon new keyboard

- .config/lf/lfrc
- .config/lf/scope
With this update, lf is now capable of displaying *.avif images seamlessly. This feature is made possible through the conversion of the avif image to a *.jpg format in the cache, which is then displayed using ueberzug.
Here is an image showing lf displaying an *.avif image
This approach not only enables lf to support avif images but also future image formats that may not be supported by ueberzug. If there are any additional image formats that need support, they can be easily added to lf in the future.
If you'd like to see this feature in action, feel free to test it out using the avif image linked [here](https://risgaard.xyz/pix/figterJet.avif)
> Add support for avif in lf

- .local/bin/shortcuts
This pull request changes the options for the `ls` command in the `shortcuts` script from `-a` to `-A`. This modification results in the script only listing almost-all files and directories, instead of all files.
- Replace `ls -a` with `ls -A` in the script file.
> Change `ls` options from `-a` to `-A` in `shortcuts` script

- .local/bin/remapd
I found a much better way of doing this, without a potentially too short sleep. This script waits for an input to be added, and then waits for a usb device to be bound. The remaps script can be run as soon as the USB device is bound. These changes should improve the reliability of the script and maybe even decrease latency. This way of doing things also doesn't require any changes to /etc/sysctl.conf.
> Clean up remapd

- .local/bin/mounter
Without this you wouldn't be able to mount android devices to `/mnt /media` or any other root directory this fixes that and the `-o allow_other` flag allows users other than root to read/write to the mounted directory.
> Fixed android device not mounting to root owned directories

- .local/bin/mounter
This does one of the items from the TODO list although it still has the problems i mentioned in my [issue](https://github.com/LukeSmithxyz/voidrice/issues/1277), and sorry if this is not very efficient and the excessive use of echo this is my level of bash scripting at the moment.
> Made mounter not show already mounted android devices in the mounting prompt

- .local/bin/maimpick
Normally when making a screenshot of an area there's still a bit of the cursor that can be seen, this hides it.
> maimpick: hide cursor when selecting area

- .config/shell/profile
- Added `SQLITE_HISTORY` env variable
- https://unix.stackexchange.com/questions/306890/change-location-of-sqlite-history-file
- https://www.sqlite.org/src/info/696e82f7c82d1720
Previously, one had to recompile the program to change the location of the file.
> SQLite ~/ cleanup

- .local/bin/dmenuunicode
It works but the good practice is to use `printf "..%s.." "$foo"` see https://www.shellcheck.net/wiki/SC2059
> dmenuunicode: don't use variables in the printf format string

- .local/bin/dmenuhandler
Shellcheck wines when printf doesn't get an argument
> fix shellcheck

- .config/lf/lfrc
In the current update, the libreoffice package doesn't have any binary for libreoffice writer, calc, impress, draw, etc. So it's better to open all of the document using the 'libreoffice' binary as it can work in the old version of libreoffice as well as the new one.
> Change LibreOffice binaries to libreoffice

- .config/ncmpcpp/config
Songs were not updating immediately in dwmblocks after song change. Added the ability for sb-music to update after a song change
> dwmblocks update on song change

- .config/lf/lfrc
It seems something is changed in how lf handles bools in lfrc. This change works for me and stops the warning.
> change requested by lf-git after update.

- .local/bin/statusbar/sb-forecast
Small PR, fixes the issue that sb-forecast wraps when the terminal is too small horizontally, now it neatly allows you to scroll
> sb-forecast: don't wrap horizontally on short terminal

- .config/lf/lfrc
As mentioned in https://github.com/gokcehan/lf/pull/1162, lf now defaults to  place the cursor at the dot if there is an extension, which breaks most of the current rename key bindings. This PR fixes that.
> Fix rename key bindings in lf

- .config/nvim/init.vim
Very arcane.
C ANSI standard requires a newline at the end. GCC will complain.[1]
Email signatures should have a space after the -- according to the standard. Neomutt does this automatically for you if you have a signature.[2]
[1]: It's in the ANSI standard pdf somewhere. Can't be bothered to find it right now. Think it is in c99 too.
[2]: https://en.wikipedia.org/wiki/Signature_block#Standard_delimiter
> Re-add whitespace to some buffer types as needed.

- .local/bin/statusbar/sb-volume
Mirrors what also happens when the user opens pulsemixer with Super+F4. 
Normally when the user opens pulsemixer with Super+F4, makes changes and closes it again, `sb-volume` gets updated. This makes it also happen when the module is left mouse clicked, as it currently doesn't update.
> Make sure sb-volume module is updated after closing pulsemixer

- .local/bin/setbg
Enables people to set a random wallpaper from a folder without any notifications at computer startup from .xprofile with `setbg -s "$HOME/wallpapers" &`.
Might have other use cases.
> Give setbg parameter to make notifications silent

- .local/bin/arkenfox-auto-update
The previous pull request on LARBS turned out not to work, so make sure `arkenfox-auto-update` runs `arkenfox-update` as the user of the profile. Otherwise it complains that it's running as root and stops.
The way of getting the username is safe, because it gets the username from the owner of the user.js file of that profile.
> Fix arkenfox pacman hook complaining about root

- .local/bin/statusbar/sb-internet
Accidentally introduced an extra space when there's a block on the right of sb-internet. This fixes it.
> Fix the extra space between sb-internet and block on the right

- .local/bin/booksplit
Apparently the -cf inside iconv tool on termux doesn't work. You have to seperate the -c and the -f in order to be able to use the script correctly on termux on android.
This probably also doesn't give issues on desktop. Please accept this pull request.
I made a issue about this here:
https://github.com/LukeSmithxyz/voidrice/issues/1357
> Fixed Booksplit for termux

- .local/bin/xdg-terminal-exec
Solves an issue where terminal wouldn't get launched when opening
an application that has `Terminal=true` in its `.desktop` file.
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2839
This works with GLib `2.76.0` and newer (released a month ago).
This is not a "proper" implementation of `xdg-terminal-exec`, but that
would require having to look for `.desktop` files of terminals and other
unnecessary stuff. This does the job and works for most terminals.
> Add xdg-terminal-exec script to launch "$TERMINAL" for .desktop files

- .config/lf/lfrc
We can simply eliminate the usage of an external tool by adding a simple case statement to handle different types of compressed files.
> Unpack Function for LF Without Aunpack

- .local/bin/statusbar/sb-music
The s/\\&/&amp;/g operation only effect is to add "amp;" after any ampersand in the artist or song name. "&" displays just fine, so there's no reason to to replace it with anything.
> Remove unessasary and counter-productive operation in sb-music

- .local/bin/dmenurecord
Fixes #1361 by returning current screen's resolution. May not be perfect if someone wants to record one screen but it at least works
> dmenurecord fix for multiple displays

- .config/lf/lfrc
The new method is more robust and better handles directory names with spaces and special characters.
It's more minimal since we get rid of 2 commands.
> An unnecessary(?), small improvement for lf mkdir command

- .config/lf/scope
Pdf previws don't appear because are generated with wrong filename.
Plain text previws with `bat` don't respect terminal theme and have annoying border.
> Fix pdf and plain text previws in lf

- .config/nvim/init.vim
Here's how the bar is supposed to look, with a special symbol for the line number and the column number, which currently doesn't render because of missing fonts:
This is how the bar currently looks :
I replaced the missing symbols with letters, and this is how it looks after this PR:
> Fix unsupported characters in vim-airline

- .config/lf/scope
This uses inkscape (v1.3) to convert. It's quick and does not open the GUI.
> lf-scope: adds SVG preview creating cache.

- .local/bin/lfub
- .local/bin/statusbar/sb-battery
- .local/bin/statusbar/sb-clock
- .local/bin/statusbar/sb-cpu
- .local/bin/statusbar/sb-cpubars
- .local/bin/statusbar/sb-disk
- .local/bin/statusbar/sb-doppler
- .local/bin/statusbar/sb-forecast
- .local/bin/statusbar/sb-help-icon
- .local/bin/statusbar/sb-internet
- .local/bin/statusbar/sb-kbselect
- .local/bin/statusbar/sb-mailbox
- .local/bin/statusbar/sb-memory
- .local/bin/statusbar/sb-moonphase
- .local/bin/statusbar/sb-music
- .local/bin/statusbar/sb-nettraf
- .local/bin/statusbar/sb-news
- .local/bin/statusbar/sb-pacpackages
- .local/bin/statusbar/sb-price
- .local/bin/statusbar/sb-tasks
- .local/bin/statusbar/sb-torrent
- .local/bin/statusbar/sb-volume
1. fix a typo in lfub
2. fix newsup exiting immediately when middle clicking the sb-news icon 
3. use setsid -f when editing statusbar scripts. this means you can interact with the scripts and see the changes you make without closing your editor.
> script fixes

- .config/zsh/.zshrc
I found it annoying when surfing in `lf` with `ctrl-o` in zsh, it would not save the history from the session before `ctrl-o`.
The option `setopt inc_append_history` fixes it by writing every command to history before it is executed. Consider also using `setopt share_history` which does the same thing but also reads the history, allowing sharing history between terminal sessions.
> Save command to Zsh history before it is executed

- .local/bin/getcomproot
The old behavior can return wrong variables. Example:
First variable named texroot outputs:
`% root = main.tex PARTITION_ROOT="$(findmnt -n -o SOURCE /)" UUID_ROOT="$(blkid -s UUID -o value "$PARTITION_ROOT")" PARTUUID_ROOT="$(blkid -s PARTUUID -o value "$PARTITION_ROOT")"`
Second:
`"$(blkid -s PARTUUID -o value "$PARTITION_ROOT")"`
Third:
`$(blkid-sPARTUUID-ovalue$PARTITION_ROOT)`
Right now, the script is more minimal, posix compliant and outputs the file correctly:
`main.tex`
> [getcomproot] - fix | minimize | posix compliance

- .config/nvim/init.vim
- .local/bin/shortcuts
Remove ranger shortcuts, it was removed in commit 05f46122b5496e43c3725558c606df83530a6daf.
Remove "nocompatible" since it is the default for Neovim.
Remove plain Vim support for NERDTreeBookmarksFile, as it is not included in LARBS.
Remove vimling, it was removed in commit a2827f76cbf4b290c8842e00d8885eb1ed5220b8.
> Remove unused vim configs and shortcuts

- .config/lf/lfrc
1. Copies the selected filename (Y currently copies filepath, not filename), and pipes it to clipboard.
2. Copies the selected filename and if it matches the yt-dlp downloaded video format [1234567891011], gets the full youtube URL and pipes it to clipboard. For example, the file "_API calls in Godot 4 under 4 minutes [hC38DsPUDVk].mkv_" pipes the string "https://www.youtube.com/watch?v=hC38DsPUDVk" to the clipboard.
3. Copies the selected filename and if it matches the yt-dlp downloaded video format [1234567891011], gets the full piped.video URL and pipes it to the clipboard. (piped.video is a mirror of youtube, even includes comments)
For the same example file as above, it pipes the string "https://piped.video/watch?v=hC38DsPUDVk" to the clipboard.
4. Opens current folder in full …
> lfrc - Added 5 new mappings, 3 of which pipe to clipboard

- .local/bin/displayselect
The `displayselect` script gets the connected displays in the variable `screens`, with each screen in a new line. When selecting 2 or more displays, the last display (secondary or tertiary) are selected by filtering out the already selected displays with `grep - v "$primary"`. 
This can be problematic in the cases where one display name is a substring of anothers name. For example: (`eDP1` and `DP1`). In this case, if `DP1` is selected as primary display, the selection of secondary display will fail, as `grep -v "DP1"` will filter out both lines.
Adjust `grep -v` pattern to avoid unintended matches by adding `^` and `$` to the searched pattern.
> Bug fix in `displayselect`

- .local/bin/maimpick
Without `-B` option, the result of the screenshot is a blank picture.
> Fix the problem when taking a screenshot of the lf window

- .local/bin/statusbar/sb-clock
In sb-clock, if date of the month is < 9 the red selection doesn't work. Is is caused by space in `date '%e'` command. I fixed it by clearing spaces using sed
```
[stepan@thinkpad ~]$ cal | sed "s/\<$(date +'%e')\>/<b><span color='red'>&<\/span><\/b>/"
December 2023
Su Mo Tu We Th Fr Sa
1  2
3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31
[stepan@thinkpad ~]$ cal | sed "s/\<$(date +'%e'|sed 's/ //g')\>/<b><span color='red'>&<\/span><\/b>/"
December 2023
Su Mo Tu We Th Fr Sa
1  2
3  4  5  6  7  <b><span color='red'>8</span></b>  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31
[stepan@thinkpad ~]$
```
> Update sb-clock to fix display issue

- .config/lf/lfrc
map gh doesn't do anything because it doesn't recognize multi-letter commands. mapping H to cd to ~
> map gh fix

- .config/lf/scope
- .local/bin/maimpick
- Added preview for `.xcf` files by using `convert`.
- Fixed `maimpick` not picking up the OCR option as the case hadn't been enabled in the script.
> (lf,maimpick) added preview for .xcf files, fixed OCR selection in dmenu script

- .local/bin/statusbar/sb-volume
the current wpctl version does not support @DEFAULT_AUDIO_SINK@, but works with @DEFAULT_SINK@
quick fix
> Fix sb-volume (toggle mute, scroll volume change)

- .config/shell/aliasrc
- .local/bin/weath
You can now add the forecast location as a parameter to weath, very useful if you want to quickly know what the weather is like somewhere else. Had to use a function because aliases don't support command line parameters.
`weath`
`weath 'Rome'`
Also added the 'cp' option so you can copy the forecast as plaintext to your clipboard, so that it can be shared. I've found myself using screenshots for it before, but that's impractical.
`weath cp`
`weath cp 'Rome'`
> weath: Add option to get forecast from a different location

- .config/lf/lfrc
Context: I accidentally pressed the C key on my .config directory and was presented with a list of directories to copy it to, then I pressed escape to quit the fzf menu without choosing anything - instead of doing nothing the script copied all of the contents inside my .config directory into my home directory. After dealing with that mess I decided to make this PR which does the following:
- Allow users to escape out of the fzf menu without unexpected copies
- Asks the user for confirmation before copying/moving files
- Some improvements in the UI
> Fix dangerous copy/move script in lf

- .local/bin/statusbar/sb-price
After the /bin/sh symlink change from bash to dash, sb-price only showed $0.00 in the statusbar. This was because the substitution in the curl command is a bashism. This PR fixes it by replacing the substitution, through fully writing it out. It also stops shellcheck from complaining.
> Fix sb-price after bash -> dash change

- .local/bin/statusbar/sb-cpu
- .local/bin/statusbar/sb-memory
Programs like Chrome run multiple processes that take up the entire notification window. This commit solves this issue by grouping and aggregating CPU and memory usage for multi-process programs into single entries.
> Group multi-process program usage

- .local/bin/sysact
This is a (subjectively) preferable behavior for locking the system.
- Pause all media players and mute audio when the system is locked. Unmute after unlocking.
> Enhance locking mechanism

- .config/shell/aliasrc
1. Remove external commands like `find`.
2. Remove extensions (possibly `.sh`) and path (`/home/username/.local/bin/`) from the names in `fzf`.
3. Only open the editor if there is a selection.
Do all of these without using `find`, `sed`, `grep`.
- First line creates an array with the files in the scripts directory.
- Second line removes path `:t` and the extensions `:r` from the scripts.
- `[[ "${c}" ]]` checks if this variable is non-empty.
- `${${(M)s:#*/${c}*}[1]} ` This works like `grep`
`(M)` enables "match" mode.
`:#` anchors the pattern to the start of each array element.
`*/${c}*` matches any path containing the selected basename.
`[1]` selects the first matching item.
> aliasrc  |  improve se()

- .local/bin/statusbar/sb-doppler
The doppler provider for Europe and Africa is permanently shut down: https://github.com/LukeSmithxyz/voidrice/issues/1394, so remove it.
I also added the national weather service of the Netherlands as doppler provider.
> Remove non-working sat24 doppler provider from sb-doppler, and add the Netherlands

- .local/bin/getbib
**EDIT AFTER 6 MONTHS:** The API changed its formatting to single line instead of as seen below. I improved the script and preserved the old output where we had entries on separate lines with tabs.
I have used and benefited from the "getbib" script and the instructions on LaTeX from Luke for a long time. So, I have put a lot of thought into this script, since I am very interested in academia. Hope you all like this.
This script stands out as a highly valuable (at least in my opinion) and efficient tool for managing and fetching BibTeX entries for DOIs found in PDF files or provided directly. The robust design and comprehensive functionality make it an indispensable asset for researchers. The main reasons for its superiority are as follows:
- **_Exceptional time-saving:_** By automating …
> Even More Improvements for Getbib (Including Prior)

- .local/bin/rssget
Searches the website for RSS feeds and adds them to newsboat url list using rssadd. Can
also find hidden RSS feeds on various websites, namely Youtube, Reddit,
Vimeo, Github, Gitlab and Medium. Gets site url as $1 or (if not present)
from X clipboard. Gets tags as $2. If it finds more than one feed, calls
dmenu for the user to choose which one to add. I have bound it to a keyboard
shortcut so i copy a site link and easily add its feed to the reader.
> rssget - search the website for RSS feeds and add them to newsboat url list (Also sites that don't give RSS links)

- .config/shell/aliasrc
Removes the need to source `.config/shell/aliasrc` after changing env vars.
> Evaluate aliases at runtime

- .config/nvim/init.vim
Neovim started showing UI rendering issues after the latest update. Some of the Unicode characters used in the vim-airline plugin were found to be the cause, this commit aims to solve the issue by removing those characters.
Check this issue for more details - https://github.com/vim-airline/vim-airline/issues/2704
> Fix UI rendering issues in neovim

- .local/bin/rssget
The script introduced in PR #1430 was mistakenly marked with `/bin/sh`, even though it uses several bashisms and isn't POSIX-compliant.
This change updates the shebang to `/bin/bash`, ensuring that the script is executed with the intended shell and preventing compatibility issues on systems where `/bin/sh` is not linked to Bash.
> Fix rssget shebang

- .config/nvim/init.vim
- Substitute `~/.config` with `${XDG_CONFIG_HOME:-$HOME/.config}` to be consistent with rest of `init.vim`.
> maint(init.vim): use `$XDG_CONFIG_HOME`
